### ISSUE TITLE
Form Manager Plugin - emitEvent: true with getter

### ISSUE THREAD

**Issue by tomsk13** [ng-state/store#6]
when emitChanges and `get` thet returns observable 
for some reason that observable is not notified about changes.

exemple : https://stackblitz.com/edit/ng-state-sample-app-bojvv2
navigate to Immer App / Todos , after entering text in the input, you will see two different values

**Comment by vytautas-pranskunas-** [comment]
Is this still an issue? Have you solved this by using function or binding to property instead of getter?

**Comment by tomsk13** [comment]
The issue is still there but the workaround is to use a function, as discussed on gitter

**Comment by vytautas-pranskunas-** [comment]
Fixed in: 7.3.0
